[package]
name = "user/pie-hiking-plugin"
description = "Plugin made for pie hiking."

version = "1.3.1"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["PieHikingPlugin.rbxm", "pie-hiking-plugin.rbxm", "**/TestPackages"]

[dev-dependencies]
heart-pie = "mariochao/heart-pie@1.0.6"
